# Add your code below

version: '3.1'

services:
  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - hyper-task-manager-network
    volumes:
      - 'mongo-data:/data/db'

  hyper-service:
    depends_on:
      - mongodb
    build:
      dockerfile: Dockerfile
      context: '.'
    container_name: hyper-task-manager
    ports:
      - "8000:8000"
    networks:
      hyper-task-manager-network:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: mongodb
      MONGO_PORT_NUMBER: 27017
    env_file:
      - .env
volumes:
  mongo-data:

networks:
  hyper-task-manager-network:


